### ISSUE TITLE
Unhappy path tests for all libs

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#10]
- [ ] ocean.py - part of [ocean.py#149](https://github.com/oceanprotocol/ocean.py/issues/149)
- [ ] ocean.js
- [ ] react

**Comment by kremalicious** [comment]
what does this mean? What needs to be done? What exactly is an unhappy path in the context of ocean.js, ocean.py and react hooks? How does it differ from https://github.com/oceanprotocol/multi-repo-issue/issues/11? What's the difference to https://github.com/oceanprotocol/ocean.py/issues/38?

**Comment by trentmc** [comment]
We have many github issues to get code coverage >x %. That will be enough, let's close this issue.
