### ISSUE TITLE
Deploy stable aqua on rinkeby/ropsten/polygon/moonbeam/mainnet and test it

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#101]
- [x] Create docker image for stable aqua (Alex)  Tag: stable-aqua
- [x] Create barge branch (Alex)  Branch:  feature/stable-aqua
- [x] Make sure that all tests are green on Ocean.js (Alex) ( [PR]https://github.com/oceanprotocol/ocean.js/pull/805l)
- [x] Make sure that all tests are green on Ocean.py (Calina)
- [x] Deploy stable aqua on all networks using URIs:  stableaqua.NETWORK.oceanprotocol.com (Marian)
- [ ] Compare the following (for all networks)
    - [ ] Total count of assets is equal
    - [ ] Random choose 20 assets and compare ddos  (regular ddo(with price object removed) has to match stable.ddo)
- [ ] Frontend tests  on all networks using the deployed images (Norbert)
    - - [ ] Mainnet
    - - [ ] Ropsten
    - - [ ] Rinkeby
    - - [ ] Moonbeam
    - - [ ] Polygon

**Comment by alexcos20** [comment]
ocean.js tests are failing:

 75 passing (15m)
  4 failing

  1) Marketplace flow
       Alice should create a FRE pricing for her asset:
     AssertionError: Unspecified AssertionError
      at /ocean/ocean.js/test/integration/Marketplaceflow.test.ts:470:5
      at step (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:33:23)
      at Object.next (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:14:53)
      at fulfilled (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:5:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) Marketplace flow
       Alice should update the FRE pricing for her asset:
     AssertionError: Unspecified AssertionError
      at /ocean/ocean.js/test/integration/Marketplaceflow.test.ts:485:5
      at step (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:33:23)
      at Object.next (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:14:53)
      at fulfilled (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:5:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  3) Marketplace flow
       Alice should create a Pool pricing for her asset:
     AssertionError: Unspecified AssertionError
      at /ocean/ocean.js/test/integration/Marketplaceflow.test.ts:508:5
      at step (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:33:23)
      at Object.next (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:14:53)
      at fulfilled (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:5:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  4) Marketplace flow
       Alice should update the POOL pricing for her asset by buying a DT:
     AssertionError: Unspecified AssertionError
      at /ocean/ocean.js/test/integration/Marketplaceflow.test.ts:519:5
      at step (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:33:23)
      at Object.next (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:14:53)
      at fulfilled (/ocean/ocean.js/test/integration/Marketplaceflow.test.ts:5:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

we need to update ocean.js

**Comment by md00ux** [comment]
When **METADATA_CACHE_URI** variable is used:
(note: **AQUARIUS_URL** variable was not explicitly set)

```shell
aquarius        | 2021-05-20 16:48:25 016416ffd407 __main__[10] INFO EventsMonitor: preparing 
aquarius        | 2021-05-20 16:48:25 016416ffd407 config[10] WARNING Config: resources.aquarius.url option is deprecated. Use resources.metadata_cache_uri instead. 
aquarius        | Traceback (most recent call last): 
aquarius        |  File "./events-monitor-main.py", line 37, in <module> 
aquarius        |    run_events_monitor() 
aquarius        |  File "./events-monitor-main.py", line 28, in run_events_monitor 
aquarius        |    monitor = EventsMonitor(setup_web3(config_file, logger), config_file) 
aquarius        |  File "/aquarius/aquarius/events/util.py", line 174, in setup_web3 
aquarius        |    _config = Config(config_file) 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/config.py", line 157, in __init__ 
aquarius        |    self._load_environ() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/config.py", line 196, in _load_environ 
aquarius        |    raise ValueError( 
aquarius        | ValueError: Both METADATA_CACHE_URI and AQUARIUS_URL envvars are set. Use only METADATA_CACHE_URI because AQUARIUS_URL is deprecated. 
aquarius        | default log level: 10, env var LOG_LEVEL DEBUG 
aquarius        | Config: resources.aquarius.url option is deprecated. Use resources.metadata_cache_uri instead. 
aquarius        | [2021-05-20 16:48:27 +0000] [12] [ERROR] Exception in worker process 
aquarius        | Traceback (most recent call last): 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker 
aquarius        |    worker.init_process() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/ggevent.py", line 146, in init_process 
aquarius        |    super().init_process() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process 
aquarius        |    self.load_wsgi() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi 
aquarius        |    self.wsgi = self.app.wsgi() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi 
aquarius        |    self.callable = self.load() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load 
aquarius        |    return self.load_wsgiapp() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp 
aquarius        |    return util.import_app(self.app_uri) 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app 
aquarius        |    mod = importlib.import_module(module) 
aquarius        |  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module 
aquarius        |    return _bootstrap._gcd_import(name[level:], package, level) 
aquarius        |  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import 
aquarius        |  File "<frozen importlib._bootstrap>", line 991, in _find_and_load 
aquarius        |  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked 
aquarius        |  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked 
aquarius        |  File "<frozen importlib._bootstrap_external>", line 783, in exec_module 
aquarius        |  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed 
aquarius        |  File "/aquarius/aquarius/run.py", line 13, in <module> 
aquarius        |    from aquarius.app.assets import assets 
aquarius        |  File "/aquarius/aquarius/app/assets.py", line 40, in <module> 
aquarius        |    ConfigProvider.set_config(OceanConfig(app.config["CONFIG_FILE"])) 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/config.py", line 157, in __init__ 
aquarius        |    self._load_environ() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/config.py", line 196, in _load_environ 
aquarius        |    raise ValueError( 
aquarius        | ValueError: Both METADATA_CACHE_URI and AQUARIUS_URL envvars are set. Use only METADATA_CACHE_URI because AQUARIUS_URL is deprecated. 
aquarius        | [2021-05-20 16:48:27 +0000] [12] [INFO] Worker exiting (pid: 12) 
aquarius        | Config: resources.aquarius.url option is deprecated. Use resources.metadata_cache_uri instead. 
aquarius        | [2021-05-20 16:48:28 +0000] [16] [ERROR] Exception in worker process 
aquarius        | Traceback (most recent call last): 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker 
aquarius        |    worker.init_process() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/ggevent.py", line 146, in init_process 
aquarius        |    super().init_process() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 134, in init_process 
aquarius        |    self.load_wsgi() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi 
aquarius        |    self.wsgi = self.app.wsgi() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/base.py", line 67, in wsgi 
aquarius        |    self.callable = self.load() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load 
aquarius        |    return self.load_wsgiapp() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp 
aquarius        |    return util.import_app(self.app_uri) 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/gunicorn/util.py", line 359, in import_app 
aquarius        |    mod = importlib.import_module(module) 
aquarius        |  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module 
aquarius        |    return _bootstrap._gcd_import(name[level:], package, level) 
aquarius        |  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import 
aquarius        |  File "<frozen importlib._bootstrap>", line 991, in _find_and_load 
aquarius        |  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked 
aquarius        |  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked 
aquarius        |  File "<frozen importlib._bootstrap_external>", line 783, in exec_module 
aquarius        |  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed 
aquarius        |  File "/aquarius/aquarius/run.py", line 13, in <module> 
aquarius        |    from aquarius.app.assets import assets 
aquarius        |  File "/aquarius/aquarius/app/assets.py", line 40, in <module> 
aquarius        |    ConfigProvider.set_config(OceanConfig(app.config["CONFIG_FILE"])) 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/config.py", line 157, in __init__ 
aquarius        |    self._load_environ() 
aquarius        |  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/config.py", line 196, in _load_environ 
aquarius        |    raise ValueError( 
aquarius        | ValueError: Both METADATA_CACHE_URI and AQUARIUS_URL envvars are set. Use only METADATA_CACHE_URI because AQUARIUS_URL is deprecated. 
aquarius        | [2021-05-20 16:48:28 +0000] [16] [INFO] Worker exiting (pid: 16)
```

**Comment by DMats** [comment]
@md00ux The issue is that both `aquarius.url` (in config.ini) and `METADATA_CACHE_URI` envvar are set.  I can tell that `aquarius.url` is set based on the presence of the log quoted below. The solution is to remove the `aquarius.url` line from config.ini

```
aquarius        | 2021-05-20 16:48:25 016416ffd407 config[10] WARNING Config: resources.aquarius.url option is deprecated. Use resources.metadata_cache_uri instead. 
```

**Comment by KatunaNorbert** [comment]
I just created a draft PR with the new URLs on the market to make the testing process easier. So if you want to check it use this link for the market deployment: https://market-h1jbjbdp6-oceanprotocol.vercel.app

**Comment by KatunaNorbert** [comment]
I get some different results using the new URLs:

**Mainnet**

- stableaqua
![Screenshot 2021-05-25 at 16 50 02](https://user-images.githubusercontent.com/37236152/119509544-66e66600-bd79-11eb-978e-8ad6f34a0a5c.png)

- aqua
![Screenshot 2021-05-25 at 16 50 12](https://user-images.githubusercontent.com/37236152/119509611-75cd1880-bd79-11eb-92b4-2b6e4c784e8f.png)


**Rinkeby**

- stableaqua
![Screenshot 2021-05-25 at 16 52 15](https://user-images.githubusercontent.com/37236152/119509798-9f863f80-bd79-11eb-9018-f79b0b71acb5.png)

- aqua
![Screenshot 2021-05-25 at 16 53 11](https://user-images.githubusercontent.com/37236152/119509914-ba58b400-bd79-11eb-9a54-3f60f0492fb4.png)


**Polygon** and **Ropsten** are fine

**Comment by KatunaNorbert** [comment]
And also I don't get the names for all the assets using the following endpoint:
https://stableaqua.rinkeby.oceanprotocol.com//api/v1/aquarius/assets/names

![Screenshot 2021-05-26 at 10 26 45](https://user-images.githubusercontent.com/37236152/119620432-a65e9200-be0d-11eb-8542-7bf19a0b261e.png)

**Comment by alexcos20** [comment]
@calina-c  ^

**Comment by alexcos20** [comment]
pool transaction history looks good on my side:
![History — Ocean Market - Google Chrome 5_31_2021 12_14_36 PM](https://user-images.githubusercontent.com/7489447/120170647-d9d45e80-c209-11eb-9cce-29b97a079cea.png)

**Comment by alexcos20** [comment]
and confirmed, I only see 3876 results, but regular aqua on rinkeby reports 5909 results

**Comment by KatunaNorbert** [comment]
Yep, pool transaction history also working for me now

![Screenshot 2021-06-01 at 12 08 37](https://user-images.githubusercontent.com/37236152/120297887-3602b580-c2d2-11eb-92e5-a8b7dfdcffe9.png)

**Comment by calina-c** [comment]
An updated version of the TODO list + questions:

- [ ] Călina & Norbert: make sure metadataCreated and metadataUpdated events are picked up and properly processed
- [ ] Purgatory testing (mainnet)
- [ ] Frontend tests on all networks using the deployed images (Norbert)
	*  Mainnet
	*  Ropsten
	*  Rinkeby
	*  Moonbeam
	*  Polygon

**Questions**:
- is the “same number of assets” test still valid, or should we adapt?
- will we sacrifice some assets (are they good ones?) for the sake of chainId, or keep the assets and drop chainId (revert most recent changes)?
