### ISSUE TITLE
Wrapped GX Token

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#105]
We need:

- [ ] Wrapped GX smartcontract
- [ ] Wrapped GX UI  to be able to swap GX <-> WGX (both ways)

see https://weth.io/

**Comment by jamiehewitt15** [comment]
@alexcos20 Do you have the weth smart contract? I couldn't see it on their website or github.

**Comment by jamiehewitt15** [comment]
Also, I haven't worked with GX so far, do they have their own network? Or which network is it deployed?

**Comment by jamiehewitt15** [comment]
@md00ux are you able to give me some details about GX? The network details and anything else that's relevant. 

I'll use this contract: https://etherscan.io/address/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2#code

**Comment by md00ux** [comment]
@jamiehewitt15 , 

You should have access now on POA nodes.

Other details:

== Blockscout:
http://18.194.204.203:4000/

==
```json
"gaiaxtestnet": {
    "DTFactory": "0x2720d405ef7cDC8a2E2e5AeBC8883C99611d893C",
    "BFactory": "0xc37F8341Ac6e4a94538302bCd4d49Cf0852D30C0",
    "FixedRateExchange": "0x3c21a90599b5B7f37014cA5Bf30d3f1b73d7e391",
    "Metadata": "0xCfDdA22C9837aE76E0faA845354f33C62E03653a",
    "Dispenser": "0x4E6058dC00e90C0DCA47A5d0D3346F409939A5ab",
    "Ocean": "0x80E63f73cAc60c1662f27D2DFd2EA834acddBaa8",
    "chainId": 2021000,
    "startBlock": 177644
}
```

**Comment by jamiehewitt15** [comment]
Great thank you very much
