### ISSUE TITLE
Labels not being assigned when creating issues

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/multi-repo-issue#108]
When you create a new issues labels were automatically assigned based on type. This stopped working after renaming the labels.

![image](https://user-images.githubusercontent.com/26000280/121376306-1579d180-c94a-11eb-8e28-3d2fddb5cf59.png)

**Comment by AnaLoznianu** [comment]
Great catch @mihaisc, I wasn't aware we have our own issue templates. 
Will do a PR asap to fix this.

**Comment by AnaLoznianu** [comment]
PR: https://github.com/oceanprotocol/.github/pull/1
