### ISSUE TITLE
Bring C2D in Barge

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#129]
Motivation:
 - with v4, you will not be able to publish an asset using your local aquarius/provider and run a compute job. Simply because the remote C2D will not be able to connect to your local provider.   You can start it , but it will fail to provision data.
 - we lack integration tests for C2D

How to:
 - create a docker container which is running kubernetes (either minikube or kind)  (WIP)
 - create a docker container that :
         - will build specific versions of C2d components (based on branches) or download public C2d images
         - prepare deployment scrips
         - connect to k8 cluster
         - deploy c2d

This is extremely complicated, requires DIND knowledge

**Comment by DMats** [comment]
Now that https://app.zenhub.com/workspace/o/oceanprotocol/barge/issues/280 is merged, can we close this issue?  @alexcos20
