### ISSUE TITLE
Code coverage weak spots

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/multi-repo-issue#134]
Identify any weak code coverage spots, write unit tests covering that functionality 

Final review of the V4 main branches 
- [x] Aquarius - done already. 96% code-coverage
- [x] Provider - done already. over 90% code-coverage
- [x] Ocean.py - done 93%, please see my last comment on this ticket

**Comment by calina-c** [comment]
I did a review on both Aquarius and Provider. Aquarius is excellently covered, while Provider could use some improvements but the uncovered code seems to be non-critical.

**Comment by calina-c** [comment]
Update on ocean.py coverage: I've added coverage and reorganised most modules, except for "models" where the discussion is of "how much" we should test. Our models are pass-throughs to contracts. During the last few weeks, a lot of functionality was deemed not to belong in ocean.py, so we should consider a ticket to analyse what we should keep in ocean.py models, and what to remove.

CC: @AnaLoznianu
