### ISSUE TITLE
Sign-up to a 3rd party bounty platform

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/multi-repo-issue#137]
Sign up with a 3rd party bug bounty platform that pays to find issues. There's a new one by the founder of defi pulse that could useful: code432n4 (code arena).
PS: Immunefi is another one

**Comment by DMats** [comment]
Immunefi is a bug bounty platform. Their website describes how projects can sign up: https://immunefi.com/projects/

code432n4 is an audit contest platform. Their docs describe the differences between bug bounties and audit contests: https://docs.code4rena.com/. If we're interested, their docs also describe how to get involved as a contest Sponsor: https://docs.code4rena.com/roles/sponsors

I skimmed them just now.  I'll take another glance at it later today and see if I can come up with a recommendation.

**Comment by DMats** [comment]
Given the original intent of this issue - to create a bug bounty - Immunefi seems like the obvious choice.  It is used for hosting bug bounty programs. Bounties can be whatever amount we choose.

Code4rena is more akin to a traditional audit in that it's timeboxed but different in that it's crowdsourced - anyone can submit a bug.

**Comment by DMats** [comment]
@alexcos20 @trentmc 

I submitted the initial request for service to Immunefi.  I expect to receive an "onboarding questionnaire" from them within 5 days.

**Comment by DMats** [comment]
I received a response from Immunefi. I'll continue to work on this task via Slack.

**Comment by AnaLoznianu** [comment]
Closing this, as we are in the process of launching a public bounty on immunify
