### ISSUE TITLE
Publisher: Capability to provider optional header part as part of Files object and included in provider consume request

### ISSUE THREAD

**Issue by soonhuat** [oceanprotocol/multi-repo-issue#145]
### **Is your feature request related to a problem? Please describe.**
To provide capability for publisher to include a header during asset publishing flow and utilize during consumption.

### **Describe the solution you'd like**
During publishing flow, publisher could provide an optional header object (key value pair, assuming is long-lived value), then provider could encrypt or decrypt as a whole Files array/object.
During consume flow, provider would decrypt and initiate the GET request with the header object if has any values.
**The header object will be set by publisher, consumer will not provide any value during consume flow.**
Sample File object structure:
```
{
    "type": "url",
    "url": "https://url.com/method",
    "header": {
      "key": "value",
      "authorization": "bearer abc...xyz",
    },
    "method": "GET"
  }
```

### **Additional context**
This feature is not same as parameterized API because this feature cover the header part and consumer would not able to provide any values, nor knowing the values.

**Comment by AnaLoznianu** [comment]
Duplicated issue of: https://github.com/oceanprotocol/provider/issues/492
