### ISSUE TITLE
Docs.oceanprotocol.com updated for V3 for react-tutorial

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#16]

**Comment by alexcos20** [comment]
replace https://github.com/oceanprotocol/react-tutorial with https://github.com/oceanprotocol/react

**Comment by trentmc** [comment]
www.oceanprotocol.com/build link changed to point to https://github.com/oceanprotocol/react

Commit:
https://github.com/oceanprotocol/site/commit/93a0917f7dbcca319d1510313bc67db9424cd8ce

**Comment by trentmc** [comment]
Last part: removed the whole React tutorial for docs. The 'quickstart' part already links to the right thing.

https://github.com/oceanprotocol/docs/commit/797009a58ab0883b6c61eab2289997acc09b2ff1

**Comment by trentmc** [comment]
PR: https://github.com/oceanprotocol/docs/pull/447

**Comment by trentmc** [comment]
Done
