### ISSUE TITLE
Epic: Balancer Configurable Rights Pool for liquidity ramp, change fee, pause pool,  whitelist LPs

### ISSUE THREAD

**Issue by 0x3bfc** [oceanprotocol/multi-repo-issue#3]
Balancer just released code [Aug 4] for "Configurable Rights Pool." We won't use it in V3.0 (unless things change) but it's good to be aware of for future releases. E.g. for liquidity ramp to go from 10% OCEAN weight to 50% weight.  It's "a smart pool factory that allows anyone to deploy smart pools with (in the reference implementation) five different rights that can be individually chosen:

- canPauseSwapping: pool creator can pause swaps (base pools can turn swapping on, but not off)
- canChangeSwapFee: pool creator can change trading fees (subject to min/max values)
- canChangeWeights: pool creator can change weights, either individually, or following a plan for gradual updates
- canAddRemoveTokens: pool creator can add/remove tokens (subject to the base pool limits)
- canWhitelistLPs: pool creator can specify a list of addresses allowed to add/remove liquidity

https://github.com/balancer-labs/configurable-rights-pool

**Comment by trentmc** [comment]
We'll be using Balancer V2 before we use this. That's scheduled in our 2021 roadmap, with corresponding epics.

So, closing this issue as redundant.
