### ISSUE TITLE
People who have consumed data can give a rating

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#32]
This is for Ocean Market.

Motivations: provide a useful / hard-to-game signal towards the quality of a dataset (promote a positive), and helps address IP rights violation (avoid a negative)(though note that IP rights violation is much less of an issue now).

- [ ] Need a means to give the rating
  - Rating can be 1 to 5 stars
  - Rating needs to get stored on-chain, signed by the rater
  - Only people who have consumed data can give a rating. It can't be just 'bought' because that's gameable: someone might buy and sell the dataset without ever looking at it. 
  - When sending the [rating], the libs can attach the txid of the order. Also, it will prevent spam due to cost (it's not going to be expensive, but not free).

- [ ] Need a means to display the rating statistics in the dataset detail page.
  - List # ratings, and average rating. 

This is all specified in (hopefully) a way that's not gameable, ie where the rating signal can be authentic.

----

There are ways to be fancier than what's given above. Those are *outside* the scope of this issue. (We have bigger fish to fry.) Things to *not* do here include: 
- a means to enter comments in addition to rating. 
- a list of all ratings by all raters, with links to the profile of each rater
- fancier statistics (e.g. show the # ratings of 1, of 2, etc like Amazon).

----
- [Nov 2, 2020] I'm labeling this as a bug, not enhancement, because it's a problem that needs solving (address IP rights violation). It's a higher-level bug, if you will.
- [Jan 11, 2021] In Nov-Dec 2020, we've solved the problem "address IP rights violation" by other means, especially the "purgatory" feature. Therefore I just removed the "bug" label. This feature still has motivations however, as I've added to the top of the description.

**Comment by SarahKay99** [comment]
Hi everyone, 

I made this PR https://github.com/oceanprotocol/market/pull/250 and I am interested in solving this problem if no one else is onto it. 

I know a lot about Ocean architecture & React apps but I am new to smart contract (Solidity) development and I need some advice on where I would begin. 

- Would I need smart contracts for this problem?
- Where do you keep your smart contracts?
- Do you have any preferences/advice on where I should put the smart contracts for the ratings?

A lot of self-learning will be involved, but if you have a minute of spare time, please send me some hints 😊

**Comment by trentmc** [comment]
@SarahKay99 Thanks very much for your interest in this issue! We appreciate your enthusiasm.

FYI while we have this issue written down here in Github, internally it's marked as "must discuss further". Why? It imposes one single rating for a dataset. Alas, that single signal is probably too over-bearing. E.g. "What does quality rating" mean?" and  "Can you trust it enough?". And so forth.

What's probably better is to have *many* signals that a user can look at, in order to make their decisions like "should I stake, should I buy, should I consume" etc. We have been going down that path for the last couple months. 

If the signal is provided natively in the app, it should have a very precise meaning that is hard to game. That's been much of our  focus in the last couple months.

But we also want to give a means for community-generated signals to be seen in the app. That's what [Market #252 issue](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/market/252) is for: "Custom signals for accounts & assets in Ocean Market" is for.

*This* issue is more readily handled if Market 252 is implemented. Then it won't need smart contracts, because any community developer can build a system for rating (with their own choice of quality measure), and then any Ocean Market user can choose to use that rating signal.

Over time, the most useful signals that emerge can be added to Ocean Market defaults.

So, @SarahKay99, my suggestion to you is: take a crack at [Market #252 issue](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/market/252). The first thing to do is refine the spec. Ideally with UX work like designing a workflow and showing wireframes. We'd be happy to review these with you. Once that is implemented, you can revisit *this* github issue by treating it as a community signal.

**Comment by kremalicious** [comment]
> Rating needs to get stored on-chain, signed by the rater

Contract update. This here needs to be solved as part of v4 or it will never get done.

**Comment by trentmc** [comment]
Or it can get done post v4. 

This is in zenhub column "low priority". It can stay there for now.

**Comment by trentmc** [comment]
Close this, just leave it to "Comments & Ratings (WIP) #1073" in market.
https://app.zenhub.com/workspaces/frontend-60acd67b133a660014278212/issues/oceanprotocol/market/1073
