### ISSUE TITLE
Write policy for Purgatory list (IP violations etc)

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#35]
Steps:
- [x] Duplicate https://github.com/github/dmca into https://github.com/oceanprotocol/dmca, without forking it, so that we can have more control. [How](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/duplicating-a-repository)
- [x] Set up dmca@oceanprotocol.com and trademark@oceanprotocol.com emails
- [x] Write and add the following. Links given are examples of how Github does it.
  * [x] [DMCA takedown policy](https://docs.github.com/en/free-pro-team@latest/github/site-policy/dmca-takedown-policy)
  * [x] [Guide to submitting a DMCA notice](https://docs.github.com/en/free-pro-team@latest/github/site-policy/guide-to-submitting-a-dmca-takedown-notice)
  * [x] [Guide to submitting a DMCA counter-notice](https://docs.github.com/en/free-pro-team@latest/github/site-policy/guide-to-submitting-a-dmca-counter-notice)
  * [x] [Trademark policy violation](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-trademark-policy)
  * [x] [Sensitive data removal policy](https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-sensitive-data-removal-policy)
  * [x] Ocean Purgatory Process
- [x] Modify files in oceanprotocol/dmca to be accurate for Ocean
- [x] Modify files to be correct for jurisdiction in case of a dispute. (SG not Northern California)
- [x] Move everything from oceanprotocol/dmca to oceanprotocol/list-purgatory/policies. [Github commit](https://github.com/oceanprotocol/list-purgatory/commit/8caab2a05bfa44ef8502da8de0346eed4828a092). New location: https://github.com/oceanprotocol/list-purgatory/tree/main/policies
- [x] Delete dmca repo, let Razvan know of move
- [x] Review with Razvan, update as needed
- [x] [Razvan] Update Ocean Market's [terms.md](https://github.com/oceanprotocol/market/blob/main/content/pages/terms.md) to reconcile with this policy. In particular, it may need an "acceptable use policy". (Example from Github)[https://docs.github.com/en/github/site-policy/github-acceptable-use-policies]

**Comment by brucepon** [comment]
I worked on the body of material.  

Suggestions:
1. I added links to Singapore IP (https://www.ipos.gov.sg/understanding-innovation-ip) and EU IP (https://europa.eu/youreurope/business/running-business/intellectual-property/index_en.htm) to https://github.com/oceanprotocol/list-purgatory/pull/3/files#diff-bbbef353cee391b3ebbaabd3379d77af5899517d29d5117f68e5a62b61c9c4d9
2. I suggest we roll Trademark Policy "https://github.com/oceanprotocol/list-purgatory/blob/41fd88594ae168c1d0e5c1b52fb28aca4db04053/policies/ocean-market-trademark-policy.md" into a more general IP infringement that is broader and includes the definitions by Singapore and the EU. For this, we should either rename the Trademark Policy to Intellectual Property Policy or fork Trademark Policy and create a new Intellectual Property Policy. For this, I need access to the repo, which I don't currently have.
3. Sensitive data policy is fine.
4. Added a statement regarding Singapore IMDA and any other Singapore government agency

**Comment by trentmc** [comment]
Thanks for the comments.

I made several small commits to reflect your tweaks to the grammar.

Then I made a commit to reflect your goal to update the IP policy. I believe it's in line with your suggestions, and I'm satisfied with it too.

**Comment by trentmc** [comment]
Bruce and Razvan have updated market/../terms.md. It's merged into the code, [here](https://github.com/oceanprotocol/market/commit/e9f8a2a50f3f1c6b4573281b7558926ea73e97b1#diff-a0169785b4e644748629c15c3fc9e09d00d4326cc791c2df0eee176e2270075b).

Which means we're done! :)
