### ISSUE TITLE
KYC support

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#39]
This is a proposal to help rug pulls & IP violations. And helps to give more reputable institutions more confidence to participate in Ocean Market.

This issue is still in early stage, hence why it's still in the "PM to discuss" column. This issue may involve non-"market/" code, so I've put it into multi-repo-issue. And right now it's more about answering Q's.

The cleanest way to get KYC support is to have it in 3box. I was DMing with Dazuck of 3box in early Dec 2021, he mentioned: "there are a few who are working on integrations so come Jan there may be some that are closer to 'readymade'. " This is great news!

Also of note: Bruce has talked with Julian of Fractals. They can link an Ethereum address to KYC credentials.  Q for Fractals:
- Does Fractals provide a bilateral link? Ie link KYC doc -> Eth address, and Eth address -> KYC doc? (If no, how does it avoid impersonation?)

Questions for PM team:
- Do we want this directly in Ocean Market? Or should we link it through a 3rd party identity system like 3Box or Keybase? (See [this issue](https://github.com/oceanprotocol/market/issues/240)). And, do any 3rd party solutions actually support that?
- If we do have it directly on Ocean Market, what GUI affordance should it be? If a label / symbol like the data partners one, what should it ? (e.g. "KYC by Fractal" or "KYC" in a tooltip? Link to KYC doc? Where's the KYC doc stored? Definitely can't "verified" because that's too strong.) 
- Should Ocean Market provide a link to *get* KYC'd

Note: this may be partly implemented via ["Custom badges for accounts in Ocean Market"](https://github.com/oceanprotocol/market/issues/252).

**Comment by kenbodnar** [comment]
Third party KYC is the way to go. That way we won't have to assign staff to keep up with changing FATF protocols.

**Comment by trentmc** [comment]
This is a longer-term issue and is being approached from other angles. Therefore, closing here.
