### ISSUE TITLE
Help community monetize: More flexible & more $ for tolls in publish, swap, consume. Referrals (bonus).

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#47]
What's good about Ocean V3 tolls:
1. a configurable, good-sized flow of revenue going to LPs (stakers / curators), with revenue+ as volume_. Via configurable % set by pool creator.
2. have *some* revenue going to marketplace runner, while not over-burdening to risk hard fork (via 0.1% toll on 'consume' for marketplace runner)
3. have *some* revenue going to Ocean community, while not over-burdening to risk hard fork (via 0.1% toll on 'consume' for Ocean community)

What could be improved (while still retaining the good from before):

1. have *more* revenue going to marketplace runner, to help them build & grow their business
   - let marketplace runner get *some* toll on AMM trading (which has 1000x volume compared to 'consume'). 
   - let marketplace runner get *good-sized* toll on AMM trading. Ideally, let them set the %, so they can calibrate.
   - how: Balancer V2 is more flexible on the flow of revenue
2. consider more options wrt 'consume' (and 'publish')
   - if the marketplace is just an AMM operator, then they don't need 'consume' fees in datatoken, they have enough revenue
   - but there should be an incentive to frontends that help with 'publish' and with 'consume'
   - how - best option: anyone who operates a service for 'consume' part can charge a fee, and it's configurable. Fee can be at smart contract level or at library level. Same for 'publish'. Ocean Market charges for each; critically, competition emerges among providers.
   - how - option: have hardcoded 'consume' % in datatokens part. But the datatoken factory can easily point to different datatoken templates that have different % values. So it's easy to change at the JS level. [MultiRepo-48](https://github.com/oceanprotocol/multi-repo-issue/issues/48)
3. have *more* revenue going to Ocean community, which in turn helps OceanDAO proposals achieve higher ROI for the same sales volume.  
   - datapoint: OpenSea and Axie Infinity charge 4.5%, and the community doesn't complain. Datapoint: DEX aggregators charge 0.5%-1.5%.
   - how - option: Ocean Market gets the fees from (1) and (2) above, and redirects them to community. Even charge super high % as an invitation to others to run their own markets (!) :)
4. incentivize people to refer people to Ocean Market etc. Example: SushiSwap referrals built into AMM. Balancer V2 will support this better.

**Comment by trentmc** [comment]
What can help:
--
[Balancer] V2 implements the option for protocol fees controlled by BAL governance on:

- Trades
- Vault withdrawals
- Flash Loans

Trade and withdrawal fees are off at inception, while Flash Loan fees will start small.

All protocol fees will be kept in the Vault.

https://twitter.com/BalancerLabs/status/1356638886756315136?s=20

**Comment by kremalicious** [comment]
What are the actionable items for this? Where is work tracked? What is the progress?

**Comment by trentmc** [comment]
Update: this has been built in Ocean V4 smart contracts and drivers. It's being handled via other issues in Ocean Market. Therefore closing here.
