### ISSUE TITLE
[EPIC] Ocean Market support for Compute-to-Data

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#53]
Define all the feature list

Disclaimer : all the ui images are not representative of the final product, their purpose is just to give a quick visual representation of the features

1. View/Search algorithms

There is a dedicated section in the market for the algorithms since they don't mix with data assets. The difference between them for filtering is `service.main.type` is either `algorithm` or `dataset`. Based on these we can split the market in `Data` and `Algorithms`.
The user needs to be able to browse the algorithm assets similar to the data assets : view paginated list of all algorithms, search and maybe filter (if it makes sense) 
![image](https://user-images.githubusercontent.com/26000280/105698966-55966580-5f0f-11eb-938d-16036b65fd46.png)

2.  Publish algorithm  (similar to dataset, but additional image, version, entrypoint)</h1>
The publish form will have the following fields: title, description, file (url of the algo), datatoken, type (compute, access), author, tags, t&c, agree with t&c check,  image (it's either the name of a docker image or the full url if it's from a 3rd party repo, ex: `node` , `oceanprotocol/algo_dockers`), version, entrypoint. We will have a list of predefined images and option for custom. If user selects custom then he will need to fill : image, version, entrypoint  
The image will be checked/validated using the docker endpoint
We will use the same pricing component as in the data assets (with fixed price and pools) 

Type : 
- compute : this is when you want  to keep your algorithm private. Compute jobs can be run with compute data sets from the same provider or data sets with an access service
- access : the algorithm can be downloaded by anyone (after buying it) . This can be used with compute data sets from any provider

![image](https://user-images.githubusercontent.com/26000280/105700296-53cda180-5f11-11eb-8089-51b15763ef02.png)

3. Edit algorithm
Same fields as with a data asset plus image, version, entrypoint . We should allow changing the file url ( currently not possible in a data asset)

4. Edit asset compute metadata (allowRawAlgo, Trusted did)

For data assets with compute services the publisher needs to edit the compute settings. Ideally we don't mix these with metadata editing because in the future there will be more options/ flows in this section.
Fields on this page : 
a) Allow raw algorithms - checkbox
b) Allow all published algorithms - checkbox
c) Publisher trusted algorithms - a list of trusted published algorithms

```
trustedAlgorithms=
{
   "did1":{
      "filesChecksum":"1234",
      "containerSectionChecksum":"7676"
   },
   "did2":{
      "filesChecksum":"1232334",
      "containerSectionChecksum":"98787"
   }
}
```
All these fields will be updated on the ddo using a helper method in ocean.js
In the first phase the data publisher will also publish it's own algorithms and add them in this section. They will add them by copying the did of the algorithm or we create a intuitive UI/UX for this action.

![image](https://user-images.githubusercontent.com/26000280/105707522-bfb50780-5f1b-11eb-88d3-77b817feeaea.png)

5. Run compute jobs

In the first implementation we will have the following flow:
- navigates to a compute data asset
- chose algorithm : raw, trusted ( do we allow public published algos? )
- start compute  job

6. Compute job history

The current compute job history should be ok, the main problem is that it's very slow. We need to move this to the graph, `ocean.assets.getOrderHistory` needs to be from [this](https://subgraph.rinkeby.oceanprotocol.com/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=query%20PoolsQuery%20%7B%0A%20%20tokenOrders(where%3A%20%7Bpayer%3A%20%220x4d156a2ef69ffddc55838176c6712c90f60a2285%22%7D)%20%7B%0A%20%20%20%20id%0A%20%20%20%20amount%0A%20%20%20%20datatokenId%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20serviceId%0A%20%20%20%20consumer%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=PoolsQuery)

![image](https://user-images.githubusercontent.com/26000280/105718223-ac109d80-5f29-11eb-92e3-a87e1e01a10b.png)
![image](https://user-images.githubusercontent.com/26000280/105718255-b6329c00-5f29-11eb-9f56-44f0e5f6ead5.png)

7. ToDo's :
- Create a data template to streamline compute-to-data
- publish 5-10 common algorithms

**Comment by kremalicious** [comment]
this is not released and we are working daily on it
