### ISSUE TITLE
[EPIC] Allow publishers to update file sizes

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/multi-repo-issue#56]
The information and the download is just updated once when a dataset is beeing created. It fetched the file size, format and availability.

In my opinion this should take place at least once every 24h or so in order to:

- show the correct file size
- alert users if the resource is broken/missing
- this would protect liquidity providers against bad actors that remove their data from their hosting platform
- this would protect liquidity providers against technical problems that just might happen
- this could inform data providers if there are any problems with their offered date to communicate fixes

Example: This file has been update several times and it now much bigger as the dataset grows. This outdated size information irritates users and buyers and might negatively affect the asset.

I would call this feature the "Data Ping" and it might be indicated by a red or green dot next to the file Icon with a timestamp for the last successful / unsuccessful ping.

Maybe it would just be enough if the data owner could trigger such a ping manually.

![image](https://user-images.githubusercontent.com/59994024/100346743-a1e32900-2fe4-11eb-83f9-e174f3db572d.png)

**Comment by trentmc** [comment]
The two issues in this epic have been completed.

Is this epic complete? If no, what does it need to be complete?

**Comment by alexcos20** [comment]
We can move this forward now, I will create the issue on the frontend size

**Comment by kremalicious** [comment]
this is solved. On the market we have replaced getting the file size from the DDO with fetching it via the provider whenever users go to an asset page. So the file size shown in UI should always reflect the actual file size, even after file has been updated at its original location.
