### ISSUE TITLE
URL validation during publish.

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#58]
Right now, market is using it's own microservice to a validate a URL that is published.
But if the URL is protected (only the provider can access it), the publish process will fail.

So instead of using that microservice, the market should call a method exposed by ocean.js which in turns call the provider to get file details and check if that URL is accessible by the provider.

**Comment by kremalicious** [comment]
Done in https://github.com/oceanprotocol/market/pull/352
