### ISSUE TITLE
Check with Kai & Robin  about the compute flows (private algo & public dataset, public algo & private dataset)

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#62]

**Comment by kaimeinke** [comment]
I am still working on my development setup and on how to expose my c2d environment and how to prepare a dataset for c2d but I am very much looking forward to discuss the flows. I will also bring Evotegra's perspective with me whenever I can.

**Comment by alexcos20** [comment]
Closing this:

1. Both use cases are needed
2. Decide which one to build on a separate issue on market
