### ISSUE TITLE
Compute-to-data example in Ocean Market -

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/multi-repo-issue#63]
We need to create a template so that data can be properly used for compute-to-data

**Comment by trentmc** [comment]
@mihaisc @alexcos20 I have a feeling this is redundant with a newer issue. If yes please close

**Comment by trentmc** [comment]
Note: the following Epic also relies on this issue: "compute-to-data example & trusted algs"
https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/ocean.py/8

**Comment by alexcos20** [comment]
@kremalicious and @mihaisc are already using demos

**Comment by mihaisc** [comment]
No, we use some random stuff that we put together that kinda makes sense, in lack of proper examples. As discussed multiple times in meetings we need proper algorithms that we publish for people to add as trusted in the beginning.

**Comment by kaimeinke** [comment]
Hi, what about the epic Titanic ML Example from Kaggle? https://www.kaggle.com/c/titanic/data 

Robin proposed it and deltaDAO likes the idea very much. Don't know about the rules/IP rights yet, but that could be a nice coop with Kaggle.

**Comment by trentmc** [comment]
Anything Kaggle will likely have IP issues.

Logistic regression is the "hello world" of ML. And scikit-learn is the probably most widely Python ML tool. Scikit-learn has a tutorial for logistic regression. I think that would be a great example. https://scikit-learn.org/stable/auto_examples/linear_model/plot_iris_logistic.html

**Comment by trentmc** [comment]
This is done thanks to the excellent efforts of @kremalicious and others.
