### ISSUE TITLE
Explore: subsidize Ocean Market gas costs

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#72]
Eth gas costs have skyrocketed. This has contributed to a slowdown in Ocean Market usage.

The goal here: explore options to fix this, with a subsidy from OPF. 

For sure subsidize the actions on publishing and consuming, but (Trent's feeling is) everything, since we want vibrant usage across the board.

Leading option so far: eth gas station.

Alex will talk to Dimo about this.

OPF is incentivized to fund this fairly generously.

**Comment by DimitarSD** [comment]
@trentmc should we close this issue since we moved forward in pursuing multi-chain?

**Comment by trentmc** [comment]
Good call. Yes let's close it.

I'll also note here: Alex built an MVP version of this for fun a couple weekends ago, and had it running successfully on ropsten or rinkeby. (Good job Alex!)
