### ISSUE TITLE
Zenhub doesn't have issue templates

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#73]
**Is your feature request related to a problem? Please describe.**

We recently got issue templates, when creating issues in GitHub. That is: when creating an issue from github.com, the template auto-appears. It helps to ensure we specify issues well, for more professional software engineering & product management practice. Great!

We do a lot of product and project management from Zenhub. It's become a core part of our product and project management flow. 

The problem: when creating an issue from Zenhub, templates don't appear, and we lose their benefits.

**Describe the solution you'd like**
In Zenhub, when creating an issue, it auto populates from templates just like GitHub does.

**Comment by kremalicious** [comment]
I can't fix ZenHub's product. ZenHub is only used by PM, all devs use GitHub as the main interface. So I would not see this here as an issue at all. Just use GitHub, and ZenHub only to organize existing issues

**Comment by kremalicious** [comment]
ZenHub only supports per-repo templates, not organization-wide templates. Test it: try to create issue in Aquarius which has repo-specific templates and they will show up. We will not edit all repos just so ZenHub works.

**Comment by trentmc** [comment]
Thanks for looking into this.

Zenhub cannot be dismissed, we write a lot issues from it. Especially PM.

If there is a way to improve issue writing practice with issue templates, we should take it. 

Most of our issues are in about 8 repos. So if we took the <1 hour to copy and paste the template for each repo, that would be the a good start.

**Comment by trentmc** [comment]
Given that zenhub pulls up templates from a github repo, that will suffice for this issue. If I notice that we're missing templates in an oft-used repo, I'll add it then.

Therefore can close.
