### ISSUE TITLE
[MULTI-CHAIN] Research Matic Network

### ISSUE THREAD

**Issue by DimitarSD** [oceanprotocol/multi-repo-issue#74]
#### What bridges are supported?

Matic supports two types of bridges: [Proof of Stake Bridge](https://docs.matic.network/docs/develop/ethereum-matic/pos/getting-started) (recommended) and [Plasma Bridge](https://docs.matic.network/docs/develop/ethereum-matic/plasma/getting-started). They also have very detailed guides/documentation on how to work with the bridges and transfer data from ETH to Matic.

#### What wallets are compatible with Matic?

- [Matic Wallet](https://matic.network/wallet/)
- Metamask
- Coinbase Wallet
- Torus
- Portis

Further information: [wallets](https://docs.matic.network/docs/develop/wallets/getting-started)

#### What potential issues/blocks we might encounter?
  - So far, no potential blocks found
  - TBA

#### TBA

-------
Useful links:

- [Ethereum↔Matic Bridge](https://docs.matic.network/docs/develop/ethereum-matic/getting-started)
- [Matic Wallet Bridge](https://wallet.matic.network/bridge)

**Comment by trentmc** [comment]
@DimitarSD I believe this can be closed?

**Comment by DimitarSD** [comment]
Yep, I'm closing it.
