### ISSUE TITLE
[MULTI-CHAIN] Research NEAR Network

### ISSUE THREAD

**Issue by DimitarSD** [oceanprotocol/multi-repo-issue#75]
#### What bridges are supported?

NEAR is using the (decentralized) [Rainbow Bridge](https://near.org/blog/eth-near-rainbow-bridge/) which comes with a dedicated [CLI](https://github.com/near/rainbow-bridge).

#### What wallets are compatible with NEAR?

[NEAR Wallet](https://wallet.near.org/)

#### What potential issues/blocks we might encounter?
  - I didn't find much info regarding Rainbow Bridge working on the NEAR/Ethereum Mainnet. It seems there are some tests ongoing. **From the NEAR dev team**: 

> currently the bridge is only live on testnet, we are working on stability and testing before launching on mainnet. You can follow progress of the bridge in our [weekly public meetings](https://www.youtube.com/results?search_query=bridge+working+group+update)

  - TBA

#### TBA

-------
Useful links:

- [NEAR Getting Started](https://docs.near.org/docs/develop/basics/getting-started)
- [ETH-NEAR Rainbow Bridge - blog post with greater explanation](https://near.org/blog/eth-near-rainbow-bridge/)
- [rainbow-bridge repo / Rainbow Bridge CLI ](https://github.com/near/rainbow-bridge)
- [Rainbow Bridge Frontend](https://near.github.io/rainbow-bridge-frontend/)
- [Rainbow Bridge Dev - Discord Channel](https://discord.com/channels/490367152054992913/801443881719169094)

**Comment by DimitarSD** [comment]
OK, I think we found a potential block for moving forward with NEAR. I updated the issue with more information. It worth keeping our eyes on it.

**Comment by trentmc** [comment]
> The Rainbow Bridge has out-of-the-box support only for generic ERC20 token transfers. More uses cases to be added in the future

Why is this an issue? To start, we only have OCEAN going back and forth, and OCEAN is a generic ERC20.

**Comment by DimitarSD** [comment]
I forgot to remove it. It's not really an issue.

**Comment by trentmc** [comment]
I believe this is complete. Closing. We can start a new issue when the time for NEAR is near.
