### ISSUE TITLE
Research OCEAN exchanges in Polygon, update docs/site accordingly

### ISSUE THREAD

**Issue by DimitarSD** [oceanprotocol/multi-repo-issue#81]
Moving forward, with OCEAN being on multiple chains, different versions of the token will appear. Like mOCEAN on the Polygon network. 

**Goals:**

- [ ] Look around to see what's already on Matic, and see if there's a first-class DEX out there, and if there is, to make sure mOCEAN can be exchanged for. Done, see comments below
- [ ] Write appropriate info in [ocean docs](https://docs.oceanprotocol.com/concepts/networks/)
- [ ] Write appropriate info in [ocean main site](https://oceanprotocol.com/token#get) (if anything is relevant)

**Comment by mihaisc** [comment]
One example of dex ( didn't test it) https://quickswap.exchange/#/swap

**Comment by DimitarSD** [comment]
It's working, I manage to swap MATIC tokens for DAI: [tx/0xeb2caaaabb8cc06b15b256fd5e175ce6f9bcdfd8c12aca2ea3a4b1a7331d3349/token-transfers](https://explorer-mainnet.maticvigil.com/tx/0xeb2caaaabb8cc06b15b256fd5e175ce6f9bcdfd8c12aca2ea3a4b1a7331d3349/token-transfers)

**Comment by trentmc** [comment]
cc Manan (@innoprenuer). Manan, I know you're doing work on this, can you report here too, and ensure you're in sync with Dimo please?

**Comment by kremalicious** [comment]
what's the status of this issue? Who is working on adding that info to docs or site?

QuickSwap is basically the default DEX in Polygon network, a fork of UniSwap code around 1 year ago. There are [multiple mOCEAN pools](https://info.quickswap.exchange/token/0x282d8efce846a88b159800bd4130ad77443fa1a1) on there, and you can farm with the LP tokens for QUICK, their governance token.

- MATIC-mOCEAN pool: https://info.quickswap.exchange/pair/0x5a94f81d25c73eddbdd84b84e8f6d36c58270510
- Swap link for mOCEAN as output: https://quickswap.exchange/#/swap?outputCurrency=0x282d8efCe846A88B159800bd4130ad77443Fa1A1

**Comment by trentmc** [comment]
Good points Matthias. I just updated the description into an actionable checklist.

@innoprenuer is this for you? Currently assigned to you. If not, perhaps for @DimitarSD ?

**Comment by trentmc** [comment]
Given the zero responses, its clear that no one cares about this issue. I agree with that! 

Since we deployed to Polygon it has not turned up as a priority. 

Closing.
