### ISSUE TITLE
Refactor DT Order handling

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#85]
Description:

When backend components are handling orders, right now they are using only the orderID  (transferTxId) and provider(using ocean.py) scans the blockchain in the past (from the contracts deployment block).  This is very inefficient (on ETH) and a blocker soon (https://blog.ethereum.org/2021/03/03/geth-v1-10-0/ - chapter "Transaction unindexing" )

(https://github.com/oceanprotocol/provider/blob/ae2abcd818fceadeb0e098180aa269b260faf37b/ocean_provider/util.py#L217  and https://github.com/oceanprotocol/ocean.py/blob/94131c50d1b478e22f6567f2afbe01ca38c07e6e/ocean_lib/models/data_token.py#L212)

Changes requested:

Every orderID(transferTxId) should be optionally send along with blockNo. 
When doing verify_order_tx:
 -   if blockNo is defined, then we only need to scan one block, making searches more efficient.
 -  else, scan the chain (inefficient, but backward compatible)

Repos affected:  ocean.py -> provider  and ocean.js

Provider:
  - for download endpoint, it will accept an optional blockNo
  - for compute start, it will accept an optional blockNo for main dataset, and optional blockNo for each additionalInputs

Frontend can use the graph to get previous valid orders, which will include both txId and blockNo

**Comment by alexcos20** [comment]
ignore it please

**Comment by alexcos20** [comment]
re-opening this

**Comment by trentmc** [comment]
Is this issue obsolete as of V4 // can we close this issue? @alexcos20
