### ISSUE TITLE
Default 'nothing allowed' state for ServiceComputePrivacy

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/multi-repo-issue#90]
At the moment, whenever a new compute data set is published all published algorithms are allowed to run on it by default, which seems unintended. This is because in the background there are some unexpected interpretations of non-existing or empty array value for `publisherTrustedAlgorithms`.

To make this more clear and explicit, we could have something like `allowAllAlgorithms` within `ServiceComputePrivacy`, set to `false` by default upon data set publish, as suggested in https://github.com/oceanprotocol/market/pull/417#issuecomment-803953523

**Comment by alexcos20** [comment]
ComputePrivacy is going to look like this:

```
export interface publisherTrustedAlgorithm {
  did: string
  filesChecksum: string
  containerSectionChecksum: string
}

export interface ServiceComputePrivacy {
  allowRawAlgorithm: boolean
  allowNetworkAccess: boolean
  allowAllPublishedAlgorithms: boolean
  publisherTrustedAlgorithms?: publisherTrustedAlgorithm[]
}
```

where:
  allowRawAlgorithm: boolean      - if you can start a compute job with a raw algorithm (drag&drop)
  allowNetworkAccess: boolean    - if you can start a compute job with a raw algorithm (drag&drop)
  allowAllPublishedAlgorithms: boolean    - if you can start a compute job with any published algorithm 
  publisherTrustedAlgorithms      - specific list of algos approved by the publisher. If this list is empty -> there are no trusted algos by the publisher.

Having allowRawAlgorithm == false && allowAllPublishedAlgorithms == false  -> only trusted algos can be started.
If publisherTrustedAlgorithms  is also empty  -> you cannot run any jobs on that dataset 

Default values on publishing:
-  allowRawAlgorithm: false
-  allowNetworkAccess: false
-  allowAllPublishedAlgorithms: false
-  publisherTrustedAlgorithms : []

**Comment by mihaisc** [comment]
> allowNetworkAccess: boolean - if algo pod has network access during compute (not implemented yet in C2D)

if the pod has no network access how does it fetch the data?

**Comment by alexcos20** [comment]
data is fetched by pod-configuration, before algo pod is created.
Algos are using data from an already mounted volume, under /data
