### ISSUE TITLE
[EPIC] Free pricing

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#91]
Actions:

- create Dispenser contract (will have the minter role for multiple DT)
- add dispenser to subgraph
- ocean.js/py support for the dispenser contract (propose minter, getDataToken)
- update market with the new pricing option (in addition to FRE, AMM)

Flows:
- publish:  when selecting Free pricing, user will call datatoken's propose minter and then dispenser activate (2 web3 calls required)
- consume: ocean lib/market can scan blockchain/query graph and if there is an active dispenser, will request 1 DT from dispenser before consumption

Old issue (kept here for history)

In order to support free assets, I'm proposing the following flow:

- market should have another dropdown/checkbox during publish form:  Free / Priced asset
- have a large cap dataToken
- move the minter role from the publisher to a Treasury Contract, which will be able to mint tokens on request (Treasury can have limits, like no more than X DT/address, maximum of X DT/ Y Blocks (dispense maximum 10 DT every 100 blocks), etc
- ocean.js/py, at consume time, if the user does not hold 1 DT, will check if faucet field exists and request 1DT from the Treasury

**Comment by trentmc** [comment]
> add a new ddo field, called faucet, which will hold the treasury smartcontract address

The problem with this is that it starts to add price-specific stuff into the data asset. That shouldn't be the case. (Remember, "price" in the "DDO" is only on the caching side, not in the chain, and that causes enough confusion on its own. I don't want to layer on more confusion).

However, good news: I think we can simply _skip_ having this. Instead, simply look at the contract attached to the the minter address; if it's a Treasury Contract then we know this asset is free and we also know the address of the Treasury Contract.

> ocean.js/py, at consume time, if the user does not hold 1 DT, will check if faucet field exists and request 1DT from the Treasury

This couples the behavior of (a) acquiring datatokens (b) consuming them. This hurts composability and maintainability. Instead, let's keep the behavior orthogonal, and the faucet should work like faucets normally work: get the token from the faucet, then consume the token.

The steps would be:
1. retrieve faucet object
2. get faucet to dispense a datatoken 
3. consume datatoken (w existing behavior)

**Comment by trentmc** [comment]
I thought of two more possible flows. Here are the three options.

**OPTION 1**

The idea in the description, with potential changes in my comment above.

Includes special Treasury Contract plus a faucet.

**OPTION 2**

- Backend - just use FRE backend (but with price=0), no extra code
- Frontend is another pricing option for the publisher, side-by-side with FRE & pools. 

**OPTION 3**

Like 2, but:
- Backend -  just use FRE backend
- Frontend - put it in "publish" step. Publisher specifies whether asset is free

----

Of the three total options, it seems that OPTION 2 is by far the simplest. Why _wouldn't_ we do it?

**Comment by alexcos20** [comment]
FRE has a 2 issues:
 - price cannot be 0  (otherwise is division by 0 and fails) (nobody though to add this exception in code, at create time requires rate > 0)
 - FRE doesn't not hold tokens, but it performs an atomic swap between publisher's wallet <-> consumer wallet. It means that the publisher always needs token in his wallet.

**Comment by alexcos20** [comment]
regarding publish:
On datatoken creation (during publishForm), cap is set to 1000.  For free assets, this cap is to small, and an attacked can drain it quickly.  so we need to be able to set the cap higher if we know that is needed.
If we add Free on pricing creation (choose between free/ fixed/dynamic), datatoken is already created and cap cannot be changed anymore

So looks like option1 is my favorite.

**Comment by trentmc** [comment]
Re FRE: ok. I looked at the [code](https://github.com/oceanprotocol/contracts/blob/master/contracts/fixedRate/FixedRateExchange.sol), yeah there could be problems in swap().

> If we add Free on pricing creation (choose between free/ fixed/dynamic), datatoken is already created and cap cannot be changed anymore

That problem will go away after NFT / V4, which separates publish from any sort of pricing / distribution of rights.

So let's split apart option 1 into four options. 

* OPTION 1A: Proposal in description; set pricing during publish. Can be done before V4.
* OPTION 1B: Proposal in description; set pricing side-by-side with FRE, AMM. Must be done after V4.
* OPTION 1C: Description + Trent's first comment; set pricing during publish. Can be done before V4.
* OPTION 1D: Description + Trent's first comment; set pricing side-by-side with FRE, AMM. Must be done after V4.

Note: "after V4: could still be done in Q2 timeframe.

I lean towards 1C & 1D, because it's a little simpler. Between those two, I'm fine with either as long as we're done by end of Q2 since it's a roadmap promise.

**Comment by alexcos20** [comment]
let's do it 1C and after V4 we move to 1D

**Comment by alexcos20** [comment]
Actions:

- create Dispenser contract (will have the minter role for multiple DT)
- add dispenser to subgraph
- ocean.js/py support for the dispenser contract (propose minter, getDataToken)
- update market with the new pricing option (in addition to FRE, AMM)

**Comment by alexcos20** [comment]
this is done, we can close it
