### ISSUE TITLE
Support Balancer V2

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/multi-repo-issue#95]
**Background/Motivation**

For Ocean V3, we did a friendly fork of Balancer V1, in order to have far lower gas fees in creating pools. (Lower fees via the ERC1167 proxy contract trick.) We reluctantly did this because it meant a larger code base with associated maintenance etc.

Balancer V2 has far lower gas fees. (Lower fees via "one big treasury" with many "pool" interfaces on top.)

We can reasonably expect that Balancer will deploy it to both Eth mainnet and Polygon, by the time we ship Ocean V4 (end of Q2).

The Balancer team has been working on a Balancer JS driver; and will appreciate our input too.

The Balancer team is working to get resources on a Balancer PY driver; and will appreciate our input too. (We can expect to input here more than in the JS driver.)

**Spec**

By the time we're done:
- Ocean `contracts` repo shouldn't have any Balancer pool stuff
- `ocean.js` should import a Balancer JS driver, which in turn uses Balancer contracts
- `ocean.py` should import a Balancer PY driver, which in turn uses Balancer contracts

**Comment by AnaLoznianu** [comment]
Closing this as we are not using Balancer v2 anymore.

**Comment by trentmc** [comment]
Reopening. We're not using Balancer V2 for initial release of Ocean V4. 

However there will be benefits to supporting it at some point:
- shared liquidity of OCEAN across all data pools at once
- access to Balancer's liquidity mining program --> higher APY for stakers, including in Ocean Data Farming
- increased optionality of pool features via Bal V2 flexibility

This needs to be traded off against the complexity increase.

Putting into "long term" for now

**Comment by kremalicious** [comment]
Not sure why this issue then still exists. By the time we get around "supporting Balancer v2" there will be Balancer v3. 

A big win for our community right now would be to simply provide liquidity into OCEAN/ETH pool on Balancer v2, then talk with their liquidity-committee to provide BAL or even BAL + OCEAN rewards for that pool. Boom, DeFi, everybody happy.

**Comment by trentmc** [comment]
Closing here, we're tracking this elsewhere - in med/longer term roadmap planning.
