### ISSUE TITLE
Switch PY repos to codeclimate

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/multi-repo-issue#97]
- [x] switch Ocean.py
 - [x] switch Provider
 - [ ] switch Aquarius
-  [x]  replace badge on Ocean.py
-  [x]  replace badge on Provider
-  [ ]  replace badge on Aquarius

**Comment by calina-c** [comment]
Blocked due to error with CodeClimate (aquarius can not be added). Waiting for support to answer.
The other 2 repos are done or in review.
